# Generated by Django 5.0.3 on 2024-03-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.FloatField(),
        ),
    ]
