# Generated by Django 5.0.3 on 2024-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_alter_history_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='source',
            field=models.CharField(default='reddit', max_length=7),
        ),
    ]
