# Generated by Django 5.0.3 on 2024-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_alter_history_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type_scrape',
            field=models.CharField(default='daily', max_length=10),
        ),
    ]
