version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=catchup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "50432:5432"

  server:
    build: server
    env_file: .env
    command: sh -c 'gunicorn --bind 0.0.0.0:8000 --chdir server server.wsgi'
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DB_NAME=catchup
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  data:
