/* tslint:disable */
/* eslint-disable */
/**
 * CatchUp API
 * CatchUp API for the CatchUp project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TokenRefresh
 */
export interface TokenRefresh {
    /**
     * 
     * @type {string}
     * @memberof TokenRefresh
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRefresh
     */
    refresh: string;
}
